namespace com.skipum.common;
using from './address';
using from './businessObject';
using from './businessPartner';
using from './carrier';
using from './codes';
using from './contentSource';
using from './currency';
using from './geographic';
using from './locale';
using from './measures';
using from './packaging';
